language: php
php:
- '7.0'
deploy:
- provider: s3
  region: eu-central-1
  access_key_id: AKIAJOQ55UAI4EP5NVSA
  secret_access_key: &1
    secure: au/UPrFdrF+9/YFB8ySFp8ecf4OlM/EyHMhDwCszM4ZJJDqPasn3BpdXd4SY9OVjnMiP5F3Se8y4C/sBtSePkBE4qg95lj/OlIL1mICumPL/VGwI+vvdXOfYmhwynMSuTjnKZWmL4wg3Rgzft+cs16gwD2Xp1C57Znx1W55+n3KVjWYuTXQPhLjArpCuy5ixWr/fJ76QmHMPs03YoDj8BsM+/AX+hqG3xCAec/HC/4I2zYEArPBI09fE61mMSndzAjEXlfCYi6u6zvUjycayWbRIDhKARc1auFV3I841EH1c8rGFBhCeHJbt1cX3Y3XeerKvQFbuXzsO3xWhcMd7KeJrY82oKNh+VB/AtgXleYahgxU0HkQibJZYF87FUBTuP4s/jZQNTfT/C87E3nd8GRdHk0MC4K2RIcGCT8NwPQRVqBZb8GBGwwn050Qzqp7/0HYi5/7dbsUKCXzIgdwtabqZ2WkkJ4YnQmyPnzxdLzGJXRbUlHxSu42UopBuuK2zDM3fT4hUiqNGvpAZk37Vyf5vfbUugmGX900zi4+J4KGcVX6kLVgKllXxEF69V0lT0nH0Og4H2aQowtMgInefOhkSBANlbLKomKj0JoGro/hl4bKV+slCIVhZimZ86PW5eI4wtWofiJ86gBWofvruvm+JxfYOUP28GeQMTpxTXMs=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: erictellier/aws-got
  bucket: aws-bucket-tellier
  upload_dir: latest
- provider: codedeploy
  region: eu-central-1
  access_key_id: AKIAJOQ55UAI4EP5NVSA
  secret_access_key: *1
  bucket: aws-bucket-tellier
  key: latest/MyApp.zip
  bundle_type: zip
  application: aws-got
  deployment_group: awsGotGrp
  on: *2
before_deploy:
- zip MyApp -r *
- mkdir -p dpl_cd_upload
- mv MyApp.zip dpl_cd_upload/MyApp.zip
script:
- phpunit --coverage-clover --bootstrap test.php
